import * as React from "react";
import Head from "next/head";
import { Layout } from "../components";
import { Formik, Form, Field, ErrorMessage } from "formik";

import { stringify } from "qs";

import calcStyles from "./calculator.module.css";

// https://demo.inksoft.com/demo?Page=Api2#methods_GetQuote

// $.ajax({
//   type: "POST",
//   url: "https://demo.inksoft.com/demo/Api2/GetQuote",
//   dataType: "text",
//   data: "QuoteItems={{QuoteItems}}&Format=JSON&OverridePricingError=false",
//   processData: false,
//   crossDomain: true,
//   success: function (res) {
//     success(res);
//   },
//   error: function (jqXHR, textStatus, ex) {
//     error(jqXHR, textStatus, ex);
//   },
// });

const QUOTE_ENDPOINT =
  "https://stores.labseven.co/Lab_Seven_Screen_Printing_Co/Api2/GetQuote";

// see https://demo.inksoft.com/demo?Page=Api2#viewModels_PricedQuoteItem
const buildQuoteItem = (productData, values) => ({
  ProductId: productData.ID,
  ProductStyleId: productData.activeStyle.ID,
  ProductStyleSizeId: productData.activeStyle.Sizes[0].ID, // assume first
  Quantity: values.Quantity,
  Sides: [
    {
      SideId: "front",
      NumColors: values.NumColors,
      ArtIdentifier: "one setup",
      IsFullColor: false,
      // OverrideDecorationMethod: "screen print",
      // SetupPriceOverride: 3.14,
      // PrintPriceOverrideEach: 3.14,
    },
  ],
});

const buildPayload = (products, values) => ({
  Format: "JSON",
  QuoteItems: products.map((product) => buildQuoteItem(product, values)),
  OverridePricingError: true,
});

const getQuote = async (products, values) => {
  const payload = buildPayload(products, values);

  let response = await fetch(QUOTE_ENDPOINT, {
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      // Accept: "application/json",
    },
    method: "POST",
    body: stringify(payload),
  });
  let json = await response.json();

  return json;
};

const validateCalculator = (values) => {
  const errors = {};
  if (Number(values.Quantity) < 1) {
    errors.Quantity = "Required";
  }
  if (Number(values.NumColors) < 1) {
    errors.NumColors = "Required";
  }
  return errors;
};

const products = [
  {
    Created: "2022-01-19T14:22:19.253Z",
    TaxExempt: false,
    HasProductArt: false,
    DesignDetailsForm: false,
    DesignOnline: true,
    BuyBlank: false,
    IsStatic: false,
    CanEmbroider: false,
    CanScreenPrint: true,
    CanDigitalPrint: false,
    CanPrint: true,
    Active: true,
    StyleCount: 0,
    SupplierId: 1000002,
    ManufacturerId: 1000075,
    ID: 1003429,
    Keywords: ["NEA100", "Era Heritage Blend Crew Tee", "New Era Apparel"],
    DecoratedProductSides: null,
    PriceRuleDiscount: null,
    Categories: [
      {
        ID: 1000004,
        Path: "T-Shirts / Mens/Unisex",
        Name: "Mens/Unisex",
      },
    ],
    Styles: [
      {
        IsHeathered: false,
        IsDarkColor: false,
        IsLightColor: false,
        Active: true,
        IsDefault: true,
        CanEmbroider: false,
        CanScreenPrint: false,
        CanDigitalPrint: false,
        CanPrint: false,
        ID: 1027173,
        Sides: [
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Black/front/500.png",
            Side: "front",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Black/front/500.png",
          },
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Black/back/500.png",
            Side: "back",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Black/back/500.png",
          },
        ],
        Sizes: [
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159318,
            Detail: {
              GTIN: "00191265599900",
            },
            SortOrder: 0,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "XS",
            ManufacturerSku: "NEA100",
            Name: "XS",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159316,
            Detail: {
              GTIN: "00191265599887",
            },
            SortOrder: 1,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Small",
            ManufacturerSku: "NEA100",
            Name: "S",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159315,
            Detail: {
              GTIN: "00191265599870",
            },
            SortOrder: 2,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Medium",
            ManufacturerSku: "NEA100",
            Name: "M",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159314,
            Detail: {
              GTIN: "00191265599863",
            },
            SortOrder: 3,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Large",
            ManufacturerSku: "NEA100",
            Name: "L",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159317,
            Detail: {
              GTIN: "00191265599894",
            },
            SortOrder: 4,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "X Large",
            ManufacturerSku: "NEA100",
            Name: "XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159311,
            Detail: {
              GTIN: "00191265599832",
            },
            SortOrder: 5,
            Weight: 8,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9,
            LongName: "2X Large",
            ManufacturerSku: "NEA100",
            Name: "2XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159312,
            Detail: {
              GTIN: "00191265599849",
            },
            SortOrder: 6,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.6,
            LongName: "3X Large",
            ManufacturerSku: "NEA100",
            Name: "3XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159313,
            Detail: {
              GTIN: "00191265599856",
            },
            SortOrder: 7,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9.6,
            LongName: "4XL",
            ManufacturerSku: "NEA100",
            Name: "4XL",
          },
        ],
        AvailableQuantityPacks: [],
        ColorwayImageFilePath_Front: null,
        ImageFilePath_Front:
          "/images/products/756/products/NEA100/Black/front/500.png",
        Name: "Black",
        HtmlColor2: null,
        HtmlColor1: "000000",
        nameCode: "black",
        href: "/product/new%20era%20apparel-nea100/black",
        hasMainImage: true,
        mainImageUrl:
          "https://stores.labseven.co/images/products/756/products/NEA100/Black/front/500.png",
      },
      {
        IsHeathered: false,
        IsDarkColor: false,
        IsLightColor: false,
        Active: true,
        IsDefault: false,
        CanEmbroider: false,
        CanScreenPrint: false,
        CanDigitalPrint: false,
        CanPrint: false,
        ID: 1027172,
        Sides: [
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Scarlet/front/500.png",
            Side: "front",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Scarlet/front/500.png",
          },
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Scarlet/back/500.png",
            Side: "back",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Scarlet/back/500.png",
          },
        ],
        Sizes: [
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159310,
            Detail: {
              GTIN: "00191265600941",
            },
            SortOrder: 0,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "XS",
            ManufacturerSku: "NEA100",
            Name: "XS",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159308,
            Detail: {
              GTIN: "00191265600927",
            },
            SortOrder: 1,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Small",
            ManufacturerSku: "NEA100",
            Name: "S",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159307,
            Detail: {
              GTIN: "00191265600910",
            },
            SortOrder: 2,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Medium",
            ManufacturerSku: "NEA100",
            Name: "M",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159306,
            Detail: {
              GTIN: "00191265600903",
            },
            SortOrder: 3,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Large",
            ManufacturerSku: "NEA100",
            Name: "L",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159309,
            Detail: {
              GTIN: "00191265600934",
            },
            SortOrder: 4,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "X Large",
            ManufacturerSku: "NEA100",
            Name: "XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159303,
            Detail: {
              GTIN: "00191265600873",
            },
            SortOrder: 5,
            Weight: 8,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9,
            LongName: "2X Large",
            ManufacturerSku: "NEA100",
            Name: "2XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159304,
            Detail: {
              GTIN: "00191265600880",
            },
            SortOrder: 6,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.6,
            LongName: "3X Large",
            ManufacturerSku: "NEA100",
            Name: "3XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159305,
            Detail: {
              GTIN: "00191265600897",
            },
            SortOrder: 7,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9.6,
            LongName: "4XL",
            ManufacturerSku: "NEA100",
            Name: "4XL",
          },
        ],
        AvailableQuantityPacks: [],
        ColorwayImageFilePath_Front: null,
        ImageFilePath_Front:
          "/images/products/756/products/NEA100/Scarlet/front/500.png",
        Name: "Scarlet",
        HtmlColor2: null,
        HtmlColor1: "922635",
        nameCode: "scarlet",
        href: "/product/new%20era%20apparel-nea100/scarlet",
        hasMainImage: true,
        mainImageUrl:
          "https://stores.labseven.co/images/products/756/products/NEA100/Scarlet/front/500.png",
      },
      {
        IsHeathered: false,
        IsDarkColor: false,
        IsLightColor: false,
        Active: true,
        IsDefault: false,
        CanEmbroider: false,
        CanScreenPrint: false,
        CanDigitalPrint: false,
        CanPrint: false,
        ID: 1027178,
        Sides: [
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Crimson/front/500.png",
            Side: "front",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Crimson/front/500.png",
          },
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Crimson/back/500.png",
            Side: "back",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Crimson/back/500.png",
          },
        ],
        Sizes: [
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159358,
            Detail: {
              GTIN: "00191265600149",
            },
            SortOrder: 0,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "XS",
            ManufacturerSku: "NEA100",
            Name: "XS",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159356,
            Detail: {
              GTIN: "00191265600125",
            },
            SortOrder: 1,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Small",
            ManufacturerSku: "NEA100",
            Name: "S",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159355,
            Detail: {
              GTIN: "00191265600118",
            },
            SortOrder: 2,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Medium",
            ManufacturerSku: "NEA100",
            Name: "M",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159354,
            Detail: {
              GTIN: "00191265600101",
            },
            SortOrder: 3,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Large",
            ManufacturerSku: "NEA100",
            Name: "L",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159357,
            Detail: {
              GTIN: "00191265600132",
            },
            SortOrder: 4,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "X Large",
            ManufacturerSku: "NEA100",
            Name: "XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159351,
            Detail: {
              GTIN: "00191265600071",
            },
            SortOrder: 5,
            Weight: 8,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9,
            LongName: "2X Large",
            ManufacturerSku: "NEA100",
            Name: "2XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159352,
            Detail: {
              GTIN: "00191265600088",
            },
            SortOrder: 6,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.6,
            LongName: "3X Large",
            ManufacturerSku: "NEA100",
            Name: "3XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159353,
            Detail: {
              GTIN: "00191265600095",
            },
            SortOrder: 7,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9.6,
            LongName: "4XL",
            ManufacturerSku: "NEA100",
            Name: "4XL",
          },
        ],
        AvailableQuantityPacks: [],
        ColorwayImageFilePath_Front: null,
        ImageFilePath_Front:
          "/images/products/756/products/NEA100/Crimson/front/500.png",
        Name: "Crimson",
        HtmlColor2: null,
        HtmlColor1: "BC3A44",
        nameCode: "crimson",
        href: "/product/new%20era%20apparel-nea100/crimson",
        hasMainImage: true,
        mainImageUrl:
          "https://stores.labseven.co/images/products/756/products/NEA100/Crimson/front/500.png",
      },
      {
        IsHeathered: false,
        IsDarkColor: false,
        IsLightColor: false,
        Active: true,
        IsDefault: false,
        CanEmbroider: false,
        CanScreenPrint: false,
        CanDigitalPrint: false,
        CanPrint: false,
        ID: 1027181,
        Sides: [
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Royal/front/500.png",
            Side: "front",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Royal/front/500.png",
          },
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Royal/back/500.png",
            Side: "back",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Royal/back/500.png",
          },
        ],
        Sizes: [
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159382,
            Detail: {
              GTIN: "00191265600781",
            },
            SortOrder: 0,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "XS",
            ManufacturerSku: "NEA100",
            Name: "XS",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159380,
            Detail: {
              GTIN: "00191265600767",
            },
            SortOrder: 1,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Small",
            ManufacturerSku: "NEA100",
            Name: "S",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159379,
            Detail: {
              GTIN: "00191265600750",
            },
            SortOrder: 2,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Medium",
            ManufacturerSku: "NEA100",
            Name: "M",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159378,
            Detail: {
              GTIN: "00191265600743",
            },
            SortOrder: 3,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Large",
            ManufacturerSku: "NEA100",
            Name: "L",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159381,
            Detail: {
              GTIN: "00191265600774",
            },
            SortOrder: 4,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "X Large",
            ManufacturerSku: "NEA100",
            Name: "XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159375,
            Detail: {
              GTIN: "00191265600712",
            },
            SortOrder: 5,
            Weight: 8,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9,
            LongName: "2X Large",
            ManufacturerSku: "NEA100",
            Name: "2XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159376,
            Detail: {
              GTIN: "00191265600729",
            },
            SortOrder: 6,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.6,
            LongName: "3X Large",
            ManufacturerSku: "NEA100",
            Name: "3XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159377,
            Detail: {
              GTIN: "00191265600736",
            },
            SortOrder: 7,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9.6,
            LongName: "4XL",
            ManufacturerSku: "NEA100",
            Name: "4XL",
          },
        ],
        AvailableQuantityPacks: [],
        ColorwayImageFilePath_Front: null,
        ImageFilePath_Front:
          "/images/products/756/products/NEA100/Royal/front/500.png",
        Name: "Royal",
        HtmlColor2: null,
        HtmlColor1: "34549E",
        nameCode: "royal",
        href: "/product/new%20era%20apparel-nea100/royal",
        hasMainImage: true,
        mainImageUrl:
          "https://stores.labseven.co/images/products/756/products/NEA100/Royal/front/500.png",
      },
      {
        IsHeathered: false,
        IsDarkColor: false,
        IsLightColor: false,
        Active: true,
        IsDefault: false,
        CanEmbroider: false,
        CanScreenPrint: false,
        CanDigitalPrint: false,
        CanPrint: false,
        ID: 1027182,
        Sides: [
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/White/front/500.png",
            Side: "front",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/White/front/500.png",
          },
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/White/back/500.png",
            Side: "back",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/White/back/500.png",
          },
        ],
        Sizes: [
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159390,
            Detail: {
              GTIN: "00191265601429",
            },
            SortOrder: 0,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "XS",
            ManufacturerSku: "NEA100",
            Name: "XS",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159388,
            Detail: {
              GTIN: "00191265601405",
            },
            SortOrder: 1,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Small",
            ManufacturerSku: "NEA100",
            Name: "S",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159387,
            Detail: {
              GTIN: "00191265601399",
            },
            SortOrder: 2,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Medium",
            ManufacturerSku: "NEA100",
            Name: "M",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159386,
            Detail: {
              GTIN: "00191265601382",
            },
            SortOrder: 3,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Large",
            ManufacturerSku: "NEA100",
            Name: "L",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159389,
            Detail: {
              GTIN: "00191265601412",
            },
            SortOrder: 4,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "X Large",
            ManufacturerSku: "NEA100",
            Name: "XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159383,
            Detail: {
              GTIN: "00191265601351",
            },
            SortOrder: 5,
            Weight: 8,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9,
            LongName: "2X Large",
            ManufacturerSku: "NEA100",
            Name: "2XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159384,
            Detail: {
              GTIN: "00191265601368",
            },
            SortOrder: 6,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.6,
            LongName: "3X Large",
            ManufacturerSku: "NEA100",
            Name: "3XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159385,
            Detail: {
              GTIN: "00191265601375",
            },
            SortOrder: 7,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9.6,
            LongName: "4XL",
            ManufacturerSku: "NEA100",
            Name: "4XL",
          },
        ],
        AvailableQuantityPacks: [],
        ColorwayImageFilePath_Front: null,
        ImageFilePath_Front:
          "/images/products/756/products/NEA100/White/front/500.png",
        Name: "White",
        HtmlColor2: null,
        HtmlColor1: "FFFFFF",
        nameCode: "white",
        href: "/product/new%20era%20apparel-nea100/white",
        hasMainImage: true,
        mainImageUrl:
          "https://stores.labseven.co/images/products/756/products/NEA100/White/front/500.png",
      },
      {
        IsHeathered: false,
        IsDarkColor: false,
        IsLightColor: false,
        Active: true,
        IsDefault: false,
        CanEmbroider: false,
        CanScreenPrint: false,
        CanDigitalPrint: false,
        CanPrint: false,
        ID: 1027187,
        Sides: [
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Graphite/front/500.png",
            Side: "front",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Graphite/front/500.png",
          },
          {
            Colorway: null,
            Height: null,
            Width: null,
            ImageFilePath:
              "/images/products/756/products/NEA100/Graphite/back/500.png",
            Side: "back",
            hasImage: true,
            imageUrl:
              "https://stores.labseven.co/images/products/756/products/NEA100/Graphite/back/500.png",
          },
        ],
        Sizes: [
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159430,
            Detail: {
              GTIN: "00191265600545",
            },
            SortOrder: 0,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "XS",
            ManufacturerSku: "NEA100",
            Name: "XS",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159428,
            Detail: {
              GTIN: "00191265600521",
            },
            SortOrder: 1,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Small",
            ManufacturerSku: "NEA100",
            Name: "S",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159427,
            Detail: {
              GTIN: "00191265600514",
            },
            SortOrder: 2,
            Weight: 6.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Medium",
            ManufacturerSku: "NEA100",
            Name: "M",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159426,
            Detail: {
              GTIN: "00191265600507",
            },
            SortOrder: 3,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "Large",
            ManufacturerSku: "NEA100",
            Name: "L",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159429,
            Detail: {
              GTIN: "00191265600538",
            },
            SortOrder: 4,
            Weight: 7.04,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.5,
            LongName: "X Large",
            ManufacturerSku: "NEA100",
            Name: "XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159423,
            Detail: {
              GTIN: "00191265600477",
            },
            SortOrder: 5,
            Weight: 8,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9,
            LongName: "2X Large",
            ManufacturerSku: "NEA100",
            Name: "2XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159424,
            Detail: {
              GTIN: "00191265600484",
            },
            SortOrder: 6,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 8.6,
            LongName: "3X Large",
            ManufacturerSku: "NEA100",
            Name: "3XL",
          },
          {
            UpCharge: 0,
            InStock: true,
            IsDefault: false,
            IsDeleted: false,
            Active: true,
            ID: 1159425,
            Detail: {
              GTIN: "00191265600491",
            },
            SortOrder: 7,
            Weight: 10.08,
            SupplierCost: null,
            LocalInventory: null,
            SupplierInventory: null,
            SaleEnd: null,
            SaleStart: null,
            SalePrice: null,
            UnitPrice: 9.6,
            LongName: "4XL",
            ManufacturerSku: "NEA100",
            Name: "4XL",
          },
        ],
        AvailableQuantityPacks: [],
        ColorwayImageFilePath_Front: null,
        ImageFilePath_Front:
          "/images/products/756/products/NEA100/Graphite/front/500.png",
        Name: "Graphite",
        HtmlColor2: null,
        HtmlColor1: "4E4E4E",
        nameCode: "graphite",
        href: "/product/new%20era%20apparel-nea100/graphite",
        hasMainImage: true,
        mainImageUrl:
          "https://stores.labseven.co/images/products/756/products/NEA100/Graphite/front/500.png",
      },
    ],
    Sides: [
      {
        Active: true,
        Regions: null,
        OverlayArtImageUrl: null,
        DisplayName: "Front",
        Name: "front",
      },
      {
        Active: true,
        Regions: null,
        OverlayArtImageUrl: null,
        DisplayName: "Back",
        Name: "back",
      },
    ],
    StoreIds: null,
    Personalizations: [],
    ProductType: "Standard",
    SalePrice: null,
    UnitPrice: 8.5,
    UnitCost: null,
    EnforceProductInventoriesSupplier: null,
    EnforceProductInventoriesLocal: null,
    StaticDesignId: null,
    MaxColors: null,
    SourceProductId: null,
    SizeChartUrl: null,
    SizeUnit: null,
    PersonalizationType: "none",
    Name: "Era Heritage Blend Crew Tee",
    Sku: "NEA100",
    Supplier: "Sanmar",
    ManufacturerSku: "NEA100",
    Manufacturer: "New Era Apparel",
    manufacturerSkuCode: "new era apparel-nea100",
    defaultHref: "/product/new%20era%20apparel-nea100/black",
    activeStyle: {
      IsHeathered: false,
      IsDarkColor: false,
      IsLightColor: false,
      Active: true,
      IsDefault: true,
      CanEmbroider: false,
      CanScreenPrint: false,
      CanDigitalPrint: false,
      CanPrint: false,
      ID: 1027173,
      Sides: [
        {
          Colorway: null,
          Height: null,
          Width: null,
          ImageFilePath:
            "/images/products/756/products/NEA100/Black/front/500.png",
          Side: "front",
          hasImage: true,
          imageUrl:
            "https://stores.labseven.co/images/products/756/products/NEA100/Black/front/500.png",
        },
        {
          Colorway: null,
          Height: null,
          Width: null,
          ImageFilePath:
            "/images/products/756/products/NEA100/Black/back/500.png",
          Side: "back",
          hasImage: true,
          imageUrl:
            "https://stores.labseven.co/images/products/756/products/NEA100/Black/back/500.png",
        },
      ],
      Sizes: [
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159318,
          Detail: {
            GTIN: "00191265599900",
          },
          SortOrder: 0,
          Weight: 6.08,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 8.5,
          LongName: "XS",
          ManufacturerSku: "NEA100",
          Name: "XS",
        },
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159316,
          Detail: {
            GTIN: "00191265599887",
          },
          SortOrder: 1,
          Weight: 6.08,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 8.5,
          LongName: "Small",
          ManufacturerSku: "NEA100",
          Name: "S",
        },
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159315,
          Detail: {
            GTIN: "00191265599870",
          },
          SortOrder: 2,
          Weight: 6.08,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 8.5,
          LongName: "Medium",
          ManufacturerSku: "NEA100",
          Name: "M",
        },
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159314,
          Detail: {
            GTIN: "00191265599863",
          },
          SortOrder: 3,
          Weight: 7.04,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 8.5,
          LongName: "Large",
          ManufacturerSku: "NEA100",
          Name: "L",
        },
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159317,
          Detail: {
            GTIN: "00191265599894",
          },
          SortOrder: 4,
          Weight: 7.04,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 8.5,
          LongName: "X Large",
          ManufacturerSku: "NEA100",
          Name: "XL",
        },
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159311,
          Detail: {
            GTIN: "00191265599832",
          },
          SortOrder: 5,
          Weight: 8,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 9,
          LongName: "2X Large",
          ManufacturerSku: "NEA100",
          Name: "2XL",
        },
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159312,
          Detail: {
            GTIN: "00191265599849",
          },
          SortOrder: 6,
          Weight: 10.08,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 8.6,
          LongName: "3X Large",
          ManufacturerSku: "NEA100",
          Name: "3XL",
        },
        {
          UpCharge: 0,
          InStock: true,
          IsDefault: false,
          IsDeleted: false,
          Active: true,
          ID: 1159313,
          Detail: {
            GTIN: "00191265599856",
          },
          SortOrder: 7,
          Weight: 10.08,
          SupplierCost: null,
          LocalInventory: null,
          SupplierInventory: null,
          SaleEnd: null,
          SaleStart: null,
          SalePrice: null,
          UnitPrice: 9.6,
          LongName: "4XL",
          ManufacturerSku: "NEA100",
          Name: "4XL",
        },
      ],
      AvailableQuantityPacks: [],
      ColorwayImageFilePath_Front: null,
      ImageFilePath_Front:
        "/images/products/756/products/NEA100/Black/front/500.png",
      Name: "Black",
      HtmlColor2: null,
      HtmlColor1: "000000",
      nameCode: "black",
      href: "/product/new%20era%20apparel-nea100/black",
      hasMainImage: true,
      mainImageUrl:
        "https://stores.labseven.co/images/products/756/products/NEA100/Black/front/500.png",
    },
    styleNameCode: "black",
  },
];

const Calculator = () => {
  const [quote, setQuote] = React.useState();
  const [error, setError] = React.useState();

  return (
    <Layout>
      <Head>
        <title>Calculator Prototype</title>
      </Head>
      <div className={calcStyles.pageContainer}>
        <h1>Calculator</h1>
        <Formik
          initialValues={{ Quantity: 50, NumColors: 2 }}
          validate={validateCalculator}
          onSubmit={async (values) => {
            setError(); // clear last error

            // TODO: remove me after DEV - helps w/ debugging
            setQuote(buildPayload(products, values));

            const res = await getQuote(products, values);
            if (res.OK) {
              setQuote(res);
            } else {
              setError(res);
            }
          }}
        >
          {({ isSubmitting }) => (
            <Form className={calcStyles.form}>
              <div className={calcStyles.formEl}>
                <label htmlFor="Quantity">Shirts</label>
                <Field id="Quantity" name="Quantity" type="number" step="1" />
                <ErrorMessage name="Quantity" component="div" />
              </div>
              <div className={calcStyles.formEl}>
                <label htmlFor="NumColors">Colors</label>
                <Field id="NumColors" name="NumColors" type="number" step="1" />
                <ErrorMessage name="NumColors" component="div" />
              </div>
              <button type="submit" disabled={isSubmitting}>
                {isSubmitting ? "..." : "Submit"}
              </button>
            </Form>
          )}
        </Formik>
        <hr />
        <div>
          <h2 style={{ display: "inline" }}>Products</h2>
          <ul>
            {products.map((product) => (
              <li key={product.ID}>
                <a href={product.defaultHref}>{`View ${product.Name}`}</a>
                <details>
                  <summary>view data</summary>
                  <pre>{JSON.stringify(products, null, 2)}</pre>
                </details>
              </li>
            ))}
          </ul>
        </div>
        <hr />
        <div>
          <h2>Endpoint</h2>
          <p>{QUOTE_ENDPOINT}</p>
        </div>
        <hr />
        <div>
          <h2>Quote Payload</h2>
          <p>As JSON</p>
          <pre>{JSON.stringify(quote, null, 2)}</pre>
          <p>
            Stringified via{" "}
            <a href="https://www.npmjs.com/package/qs">
              https://www.npmjs.com/package/qs
            </a>
          </p>
          <pre>{stringify(quote)}</pre>
        </div>
        <hr />
        <div>
          <h2>Error</h2>
          <pre>{JSON.stringify(error, null, 2)}</pre>
        </div>
      </div>
    </Layout>
  );
};

export default Calculator;
